- name: Create vkteams dir
  file:
    path: /opt/vkteams
    state: directory
  become: true
  register: no_vkteams

- name: download vk-teams
  unarchive:
    src: "https://vkteams-www.hb.bizmrg.com/linux/x64/vkteams.tar.xz"
    dest: /opt/vkteams
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  become: true
  when: no_vkteams is changed

- name: Create simlink vk-teams
  file:
    src: /opt/vkteams/vkteams
    dest: /usr/local/bin/vkteams
    state: link
  become: true

- name: Create shortcut Vkteams
  copy:
    src: files/vkteams.desktop
    dest: /usr/share/applications/vkteams.desktop
    mode: 0644
  become: true
    

- name: Install rocket.chat
  community.general.snap:
    name: rocketchat-desktop
  become: true

- name: Add telegram repo
  apt_repository:
    repo: ppa:atareao/telegram

- name: Install telegram
  apt:
    pkg:
      - telegram
    state: present
  become: true

- name: Remove old telegram
  apt:
    pkg:
      - telegram-desktop
    state: absent
  become: true