- name: install tinyproxy
  apt:
    name: tinyproxy
    state: latest
    update_cache: yes
  become: true

- name: add tinyproxy config
  template:
    src: tinyproxy.conf.j2
    dest: /etc/tinyproxy/tinyproxy.conf
    owner: root
    group: root
    mode: 0640
  become: true
  register: update_config

- name: restart tinyproxy
  systemd:
    name: tinyproxy
    state: restarted
    enabled: yes
  become: true
  when: update_config is changed
