- name: find network configs
  find:
    paths: /etc/netplan/
    excludes: '01-netcfg.yaml'
  register: config_files


- name: delete network configs
  file:
    state: absent
    path: "{{ item.path }}"
  with_items: "{{ config_files.files }}"
  become: true
  register: delete_configs

- name: add network config
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0640
  become: true
  register: update_config

- name: disable
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  become: true
  loop:
    - NetworkManager-wait-online
    - NetworkManager-dispatcher
    - network-manager.service
    - NetworkManager
  ignore_errors: true
- name: delete Network Manager
  apt:
    name: network-manager
    state: absent
    purge: true
  become: true

- name: Install network-manager from snap
  community.general.snap:
    name: network-manager
    options:
     - defaultrenderer=false
  become: true

- name: update config
  shell: netplan apply
  become: true
  when: update_config is changed or delete_configs is changed