- name: clear configs
  file:
    state: "{{ item }}"
    path: "/etc/netplan/"
    owner: root # set your owner, group, and mode accordingly
    group: root
    mode: '0755'
  with_items:
    - absent
    - directory
  become: true

- name: add network config
  template:
    src: 01-netcfg.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    owner: root
    group: root
    mode: 0640
  become: true

- name: update config
  shell: netplan apply
  become: true

- name: disable
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  become: true
  loop:
    - NetworkManager-wait-online
    - NetworkManager-dispatcher
    - network-manager.service
    - NetworkManager
    - networkd-dispatcher
  ignore_errors: true
- name: delete Network Manager
  apt:
    name: network-manager
    state: absent
    purge: true
  become: true
