# Go language SDK version number
golang_version: '1.22.0'

# Mirror to download the Go language SDK redistributable package from
golang_mirror: 'https://go.dev/dl'

# Base installation directory the Go language SDK distribution
golang_install_dir: '/opt/go/{{ golang_version }}'

# Directory to store files downloaded for Go language SDK installation
golang_download_dir: "{{ x_ansible_download_dir | default(ansible_facts.env.HOME + '/.ansible/tmp/downloads') }}"

golang_filename: "go{{ golang_version }}.linux-amd64.tar.gz"

# Location for GOPATH environment variable
golang_gopath: