- name: install base packages
  apt:
    pkg:
      - bash
      - vim
      - nano
      - git
      - keepass2
      - nmap
      - traceroute
      - chromium-browser
      - shutter
    state: present
    update_cache: true
  become: true

- name: Set a hostname
  hostname:
    name: "{{ hostname }}"

- name: setup git configs
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0664
