- name: install 
  apt:
    name: openssh-server
    state: latest
    update_cache: yes
  become: true
  register: install_sshd
- name: start srvice
  systemd:
    name: ssh
    state: restarted
    enabled: yes
  when: install_sshd is changed
  become: true